name: Access Secret Example

on:
  push:
    branches:
      - main

jobs:
  accessSecret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Access API key
        run: echo ${{ secrets.API_KEY }} >> ./api-key.txt

      - name: Display API key
        run: cat ./api-key.txt
